stable_task:
  container:
    image: rust:latest
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cargo update && cat Cargo.lock
  env:
    matrix:
      - CRATE: oxide-auth
      - CRATE: oxide-auth-async
      - CRATE: oxide-auth-actix
      - CRATE: actix-example
      - CRATE: oxide-auth-iron
      - CRATE: oxide-auth-rouille
      - CRATE: db-example
  build_script: cargo build -p "$CRATE" --examples
  test_script: cargo test -p "$CRATE"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

stable_auth_db_task:
  container:
    image: rust:latest
  additional_containers:
    - name: redis
      image: redis:latest
      port: 6379
      cpu: 0.5
      memory: 128Mi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cargo update && cat Cargo.lock
  env:
      OXIDE_REDIS_DSN: redis://localhost:6379/3
  build_script: cargo build -p "oxide-auth-db" --examples
  test_script: cargo test -p "oxide-auth-db"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

nightly_task:
  container:
    image: rustlang/rust:nightly
  additional_containers:
    - name: redis
      image: redis:latest
      port: 6379
      cpu: 0.5
      memory: 128Mi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cargo update && cat Cargo.lock
  env:
    matrix:
      - CRATE: oxide-auth
      - CRATE: oxide-auth-async
      - CRATE: oxide-auth-actix
      - CRATE: actix-example
      - CRATE: oxide-auth-iron
      - CRATE: oxide-auth-rouille
      - CRATE: oxide-auth-rocket
      - CRATE: db-example
  build_script: cargo build -p "$CRATE" --examples
  test_script: cargo test -p "$CRATE"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

nightly_auth_db_task:
  container:
    image: rust:nightly
  additional_containers:
    - name: redis
      image: redis:latest
      port: 6379
      cpu: 0.5
      memory: 128Mi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cargo update && cat Cargo.lock
  env:
    OXIDE_REDIS_DSN: redis://localhost:6379/3
  build_script: cargo build -p "oxide-auth-db" --examples
  test_script: cargo test -p "oxide-auth-db"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

release_task:
  only_if: $CIRRUS_BRANCH =~ 'release.*'
  container:
    image: rust:latest
  script: ./release

doc_task:
  container:
    image: rustlang/rust:nightly
  script: cargo doc --no-deps --document-private-items --all-features

